"""annotation tables

Revision ID: dd05735f162f
Revises: 
Create Date: 2025-06-04 13:00:21.992940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd05735f162f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('annotationTXT_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('piece_image_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'annotationTXT_name', name=op.f('pk_annotation')),
    schema='annotation'
    )
    op.create_index(op.f('ix_annotation_annotation_id'), 'annotation', ['id'], unique=False, schema='annotation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_annotation_id'), table_name='annotation', schema='annotation')
    op.drop_table('annotation', schema='annotation')
    # ### end Alembic commands ###
