"""artifact_keeper tables

Revision ID: 42c2eed02097
Revises: 
Create Date: 2025-06-03 09:29:49.402746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c2eed02097'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameraSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exposure', sa.Float(), nullable=True),
    sa.Column('contrast', sa.Float(), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('focus', sa.Float(), nullable=True),
    sa.Column('aperture', sa.Float(), nullable=True),
    sa.Column('gain', sa.Integer(), nullable=True),
    sa.Column('white_balance', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameraSettings')),
    schema='artifact_keeper'
    )
    op.create_index(op.f('ix_artifact_keeper_cameraSettings_id'), 'cameraSettings', ['id'], unique=False, schema='artifact_keeper')
    op.create_table('piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_data_id', sa.Integer(), nullable=True),
    sa.Column('piece_label', sa.String(), nullable=False),
    sa.Column('is_annotated', sa.Boolean(), nullable=True),
    sa.Column('is_yolo_trained', sa.Boolean(), nullable=True),
    sa.Column('nbre_img', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_piece')),
    sa.UniqueConstraint('piece_label', name=op.f('uq_piece_piece_label')),
    schema='artifact_keeper'
    )
    op.create_index(op.f('ix_artifact_keeper_piece_id'), 'piece', ['id'], unique=False, schema='artifact_keeper')
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_index', sa.Integer(), nullable=True),
    sa.Column('camera_type', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('settings_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['settings_id'], ['artifact_keeper.cameraSettings.id'], name=op.f('fk_camera_settings_id_cameraSettings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera')),
    sa.UniqueConstraint('serial_number', name=op.f('uq_camera_serial_number')),
    schema='artifact_keeper'
    )
    op.create_index(op.f('ix_artifact_keeper_camera_id'), 'camera', ['id'], unique=False, schema='artifact_keeper')
    op.create_index(op.f('ix_artifact_keeper_camera_model'), 'camera', ['model'], unique=False, schema='artifact_keeper')
    op.create_table('piece_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['artifact_keeper.piece.id'], name=op.f('fk_piece_image_piece_id_piece')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_piece_image')),
    schema='artifact_keeper'
    )
    op.create_index(op.f('ix_artifact_keeper_piece_image_id'), 'piece_image', ['id'], unique=False, schema='artifact_keeper')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_keeper_piece_image_id'), table_name='piece_image', schema='artifact_keeper')
    op.drop_table('piece_image', schema='artifact_keeper')
    op.drop_index(op.f('ix_artifact_keeper_camera_model'), table_name='camera', schema='artifact_keeper')
    op.drop_index(op.f('ix_artifact_keeper_camera_id'), table_name='camera', schema='artifact_keeper')
    op.drop_table('camera', schema='artifact_keeper')
    op.drop_index(op.f('ix_artifact_keeper_piece_id'), table_name='piece', schema='artifact_keeper')
    op.drop_table('piece', schema='artifact_keeper')
    op.drop_index(op.f('ix_artifact_keeper_cameraSettings_id'), table_name='cameraSettings', schema='artifact_keeper')
    op.drop_table('cameraSettings', schema='artifact_keeper')
    # ### end Alembic commands ###
