"""art_keeper tables v2

Revision ID: 4d16b7146141
Revises: 822b87108b9a
Create Date: 2025-05-23 15:16:28.780106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d16b7146141'
down_revision: Union[str, None] = '822b87108b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameraSettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exposure', sa.Float(), nullable=True),
    sa.Column('contrast', sa.Float(), nullable=True),
    sa.Column('brightness', sa.Float(), nullable=True),
    sa.Column('focus', sa.Float(), nullable=True),
    sa.Column('aperture', sa.Float(), nullable=True),
    sa.Column('gain', sa.Integer(), nullable=True),
    sa.Column('white_balance', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameraSettings')),
    schema='artifact_keeper'
    )
    op.create_index(op.f('ix_artifact_keeper_cameraSettings_id'), 'cameraSettings', ['id'], unique=False, schema='artifact_keeper')
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_index', sa.Integer(), nullable=True),
    sa.Column('camera_type', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('settings_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['settings_id'], ['artifact_keeper.cameraSettings.id'], name=op.f('fk_camera_settings_id_cameraSettings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_camera')),
    sa.UniqueConstraint('serial_number', name=op.f('uq_camera_serial_number')),
    schema='artifact_keeper'
    )
    op.create_index(op.f('ix_artifact_keeper_camera_id'), 'camera', ['id'], unique=False, schema='artifact_keeper')
    op.create_index(op.f('ix_artifact_keeper_camera_model'), 'camera', ['model'], unique=False, schema='artifact_keeper')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifact_keeper_camera_model'), table_name='camera', schema='artifact_keeper')
    op.drop_index(op.f('ix_artifact_keeper_camera_id'), table_name='camera', schema='artifact_keeper')
    op.drop_table('camera', schema='artifact_keeper')
    op.drop_index(op.f('ix_artifact_keeper_cameraSettings_id'), table_name='cameraSettings', schema='artifact_keeper')
    op.drop_table('cameraSettings', schema='artifact_keeper')
    # ### end Alembic commands ###
