"""tables v3

Revision ID: 9fdebec8bb89
Revises: 4d16b7146141
Create Date: 2025-05-24 21:52:53.766317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fdebec8bb89'
down_revision: Union[str, None] = '4d16b7146141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piece',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_data_id', sa.Integer(), nullable=True),
    sa.Column('piece_label', sa.String(), nullable=False),
    sa.Column('is_annotated', sa.Boolean(), nullable=True),
    sa.Column('is_yolo_trained', sa.Boolean(), nullable=True),
    sa.Column('nbre_img', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_piece')),
    sa.UniqueConstraint('piece_label', name=op.f('uq_piece_piece_label')),
    schema='artifact_keeper'
    )
    op.create_index(op.f('ix_artifact_keeper_piece_id'), 'piece', ['id'], unique=False, schema='artifact_keeper')
    op.create_foreign_key(op.f('fk_piece_image_piece_id_piece'), 'piece_image', 'piece', ['piece_id'], ['id'], source_schema='artifact_keeper', referent_schema='artifact_keeper')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_piece_image_piece_id_piece'), 'piece_image', schema='artifact_keeper', type_='foreignkey')
    op.drop_index(op.f('ix_artifact_keeper_piece_id'), table_name='piece', schema='artifact_keeper')
    op.drop_table('piece', schema='artifact_keeper')
    # ### end Alembic commands ###
