version: "3.9"

services:
  user_management:
    container_name: userManagementMicroservice
    build:
      context: ./backend/user_management
    env_file:
      - ./.env
    ports:
      - "8001:8000"
    depends_on:
      - databasePostgres
    networks:
      - airvision-net
    volumes:
      - ./backend/user_management:/usr/srv/user_management
      - ./.env:/usr/srv/.env  
    # Remove the custom command that tries to copy the entrypoint
    # command: ["bash", "-c", "cp /app/entrypoint.sh /tmp/entrypoint.sh && chmod +x /tmp/entrypoint.sh && /tmp/entrypoint.sh"]

  databasePostgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airbususer -d airvisiondb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - airvision-net
    ports:
      - "5433:5432"

  airbus_ui:
    build:
      context: .
      dockerfile: ./airbus_ui/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - user_management  
    networks:
      - airvision-net

networks:
  airvision-net:

volumes:
  user_postgres_data:
  defect_postgres_data: