version: "3.9"

services:
  user_management:
    container_name: userManagement
    build:
      context: ./backend/user_management
    env_file:
      - ./backend/user_management/.env
    ports:
      - "8001:8000"
    depends_on:
      - user-postgres
    networks:
      - airbus-net
    volumes:
      - ./backend/user_management:/usr/srv/user_management

  user-postgres:
    image: postgres:15
    container_name: userpostgres
    restart: unless-stopped
    env_file:
      - ./backend/user_management/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airbususer -d userdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - airbus-net
    ports:
      - "5433:5432"

  airbus_ui:
    build:
      context: .
      dockerfile: ./airbus_ui/Dockerfile
    ports:
      - "3000:80"
    networks:
      - airbus-net

networks:
  airbus-net:

volumes:
  user_postgres_data:
  defect_postgres_data:
