"""recreate user table~

Revision ID: a55bf11582de
Revises: 1019000e623e
Create Date: 2025-04-30 09:45:38.575187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a55bf11582de'
down_revision: Union[str, None] = '1019000e623e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_code', sa.String(length=8), nullable=True))
    op.add_column('users', sa.Column('activation_code_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_code_expires_at')
    op.drop_column('users', 'activation_code')
    # ### end Alembic commands ###
