"""detection microservice tables

Revision ID: 965855fe092d
Revises: 
Create Date: 2025-08-02 18:10:07.669831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965855fe092d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_lot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_name', sa.String(), nullable=False),
    sa.Column('expected_piece_id', sa.Integer(), nullable=False),
    sa.Column('expected_piece_number', sa.Integer(), nullable=False),
    sa.Column('is_target_match', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_lot')),
    schema='detection'
    )
    op.create_index(op.f('ix_detection_detection_lot_id'), 'detection_lot', ['id'], unique=False, schema='detection')
    op.create_table('detection_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('correct_pieces_count', sa.Integer(), nullable=True),
    sa.Column('misplaced_pieces_count', sa.Integer(), nullable=True),
    sa.Column('total_pieces_detected', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_target_match', sa.Boolean(), nullable=True),
    sa.Column('detection_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['detection.detection_lot.id'], name=op.f('fk_detection_session_lot_id_detection_lot')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_session')),
    schema='detection'
    )
    op.create_index(op.f('ix_detection_detection_session_id'), 'detection_session', ['id'], unique=False, schema='detection')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_detection_session_id'), table_name='detection_session', schema='detection')
    op.drop_table('detection_session', schema='detection')
    op.drop_index(op.f('ix_detection_detection_lot_id'), table_name='detection_lot', schema='detection')
    op.drop_table('detection_lot', schema='detection')
    # ### end Alembic commands ###
