"""table training creation

Revision ID: 6be7a4bc5b7f
Revises: 
Create Date: 2025-07-02 11:07:25.518310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be7a4bc5b7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=True),
    sa.Column('epochs', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.Column('device_used', sa.String(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_accuracy', sa.Float(), nullable=True),
    sa.Column('final_loss', sa.Float(), nullable=True),
    sa.Column('model_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_session')),
    schema='training'
    )
    op.create_index(op.f('ix_training_training_session_id'), 'training_session', ['id'], unique=False, schema='training')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_training_session_id'), table_name='training_session', schema='training')
    op.drop_table('training_session', schema='training')
    # ### end Alembic commands ###
