"""create training table

Revision ID: ddfd25086edf
Revises: 
Create Date: 2025-06-30 15:48:39.369795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfd25086edf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_session', sa.Column('piece_id', sa.Integer(), nullable=True), schema='training')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_session', 'piece_id', schema='training')
    # ### end Alembic commands ###
